apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: api-gateway
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: conf
        image: ghcr.io/luka-j/matf-rs2-api-gateway-frontend:sha-9eda5a55eb9c8c224f0aa36f81f25ef40483c8f6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080