apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: api-gateway
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: conf
        image: ghcr.io/luka-j/matf-rs2-api-gateway-frontend:sha-a43213f33d0020d4d95f8709e39a34874321b57e
        imagePullPolicy: Always
        ports:
        - containerPort: 8080