apiVersion: apps/v1
kind: Deployment
metadata:
  name: cco-deployment
  namespace: api-gateway
  labels:
    app: cco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cco
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: cco
    spec:
      containers:
      - name: conf
        image: ghcr.io/luka-j/matf-rs2-api-gateway-cco:sha-7b792610a2352f53b0cb74e909ab99b9b94c94a9
        imagePullPolicy: Always
        ports:
        - containerPort: 80
