apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api-gateway
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/luka-j/matf-rs2-api-gateway-api:sha-193c18a1371961de436b78585fa68026efc379e8
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 8080
