apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-deployment
  namespace: api-gateway
  labels:
    app: conf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conf
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: conf
    spec:
      containers:
      - name: conf
        image: ghcr.io/luka-j/matf-rs2-api-gateway-conf:sha-6f5adb31bd9fd8ed7e818e10574e7cc37802482b
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
