apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf-deployment
  namespace: api-gateway
  labels:
    app: conf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conf
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: conf
    spec:
      serviceAccountName: conf-sa
      containers:
      - name: conf
        image: ghcr.io/luka-j/matf-rs2-api-gateway-conf:sha-d0919c506b8ef091c84cb5c86c3e17d4d7dc4ff3
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: "UseKubernetes"
          value: "true"
        - name: "GitHubSettings__UseGitHub"
          value: "true"
        - name: "GitHubSettings__GitHubRepoURL"
          value: "https://github.com/vita-ride/rs2-config-repo.git"
        - name: "GitHubSettings__GitHubRepoName"
          value: "rs2-config-repo"
        - name: "GitHubSettings__PAT"
          valueFrom:
            secretKeyRef:
              name: conf-secret
              key: github_pat
        - name: "GitHubSettings__GitUserName"
          valueFrom:
            secretKeyRef:
              name: conf-secret
              key: github_username
        - name: "GithubSettings__GitPassword"
          valueFrom:
             secretKeyRef:
               name: conf-secret
               key: github_password
        - name: "AuthSettings__UseAuth"
          value: "false"
        - name: "AuthSettings__AuthUrl"
          value: "https://github.com/vita-ride/rs2-config-repo.git"
