apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-services
  namespace: api-gateway
subjects:
- kind: User
  name: conf-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: resource-reader
  apiGroup: rbac.authorization.k8s.io