apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api-gateway
  name: resource-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]