apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luka-j/matf-rs2-api-gateway.git
    targetRevision: refs/heads/master
    path: frontend/k8s-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
