apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-community/kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.2.3
    helm:
      releaseName: kube-prometheus-stack
      values: |
          grafana:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
              - grafana-rs2.luka-j.rocks
              tls:
              -  secretName: grafana-tls-secret
                 hosts:
                  - grafana-rs2.luka-j.rocks
          prometheus:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
              - prometheus-rs2.luka-j.rocks
              tls:
              -  secretName: prometheus-tls-secret
                 hosts:
                  - prometheus-rs2.luka-j.rocks
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
