apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-deployment
  namespace: api-gateway
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rp
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: rp
    spec:
      containers:
      - name: api
        image: ghcr.io/luka-j/matf-rs2-api-gateway-rp:sha-fa4bd63dc9286fc49997561399379e0c9f38fb24
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
