apiVersion: v1
kind: Service
metadata:
  name: rp-service
  namespace: api-gateway
spec:
  selector:
    app: api
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
