{
 "title": "API monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frontend errors / min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code, path, status) (increase(apigtw_http_request_errors[1m]))",
     "legendFormat": "{{code}} {{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "Backend errors / min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (api_name, api_version, endpoint, method, code) (increase(apigtw_service_request_errors[1m]))",
     "legendFormat": "{{code}} - {{api_name}}/{{api_version}} {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Frontend requests / min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (api_name, api_version, endpoint, method, status, response_code) (increase(apigtw_api_request_time_count[1m]))",
     "legendFormat": "{{response_code}} {{status}} - {{api_name}}/{{api_version}}: {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Backend requests / min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (api_name, api_version, endpoint, method, status, response_code) (increase(apigtw_service_request_time_count[1m]))",
     "legendFormat": "{{response_code}} {{status}} - {{api_name}}/{{api_version}}: {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Frontend request time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version, endpoint, method, status, response_code) (increase(apigtw_api_request_time_sum[1m]) / increase(apigtw_api_request_time_count[1m]))",
     "legendFormat": "{{response_code}} {{status}} - {{api_name}}/{{api_version}}: {{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Backend request time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version, endpoint, method, status, response_code) (increase(apigtw_service_request_time_sum[1m]) / increase(apigtw_service_request_time_count[1m]))",
     "legendFormat": "{{response_code}} {{status}} - {{api_name}}/{{api_version}}: {{method}} {{endpoint}}"
    }
   ]
  }
 ]
}